apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespaces.app }}
spec:
  vaultAuthRef: app-auth
  mount: "database"
  path: {{ .Values.vsoObjects.dbCredsPath | quote }}
  refreshAfter: {{ .Values.secret.refreshAfter | quote }}
  revoke: true
  destination:
    name: {{ .Values.secret.name }}
    create: true
    transformation:
      templates:
        {{ .Values.secret.mapping.userKey }}:
          text: '{{ "{{ get .Secrets \"username\" }}" }}'
        {{ .Values.secret.mapping.passKey }}:
          text: '{{ "{{ get .Secrets \"password\" }}" }}'
        {{ .Values.secret.mapping.hostKey }}:
          text: '{{ printf "%s.%s.svc" .Values.zalando.name .Values.zalando.namespace }}'
        {{ .Values.secret.mapping.portKey }}:
          text: '{{ .Values.appDb.port }}'
        {{ .Values.secret.mapping.nameKey }}:
          text: '{{ .Values.appDb.dbName }}'
        {{ .Values.secret.mapping.urlKey }}:
          text: '{{ printf "postgresql://%s:%s@%s.%s.svc:%s/%s" "{{ get .Secrets \"username\" }}" "{{ get .Secrets \"password\" }}" .Values.zalando.name .Values.zalando.namespace .Values.appDb.port .Values.appDb.dbName }}'
